## Introduction

There is a strong, widespread and increasing demand for NSIs to release Microdata Files (MF), that is, data sets containing for each respondent the score on a number of variables. 
Microdata files are samples generated from business or social surveys or from the Census or originate from administrative sources. It is in the interest of users 
to make the microdata as detailed as possible but this interest conflicts with the obligation that NSIs have to protect the confidentiality of the information 
provided by the respondent.

In @sec-concepts-and-definitions two definitions of disclosure were provided: re-identification disclosure and attribute disclosure. 
In the microdata setting the re-identification disclosure concept is used as we are releasing information at individual level. 
When releasing microdata, an NSI must assess the risk of re-identifying statistical units and disclosing confidential information. 
There are different options available to NSIs for managing these disclosure risks, namely applying statistical disclosure control techniques, restricting access or 
a combination of the two.

Applying SDC methods leads to a loss of information and statistical content and affects the inferences that users are able to make on the data. 
The goal for an effective statistical disclosure control strategy is to choose optimum SDC techniques which maximize the utility of the data while minimizing the disclosure risk\index{disclosure risk}. 
On the other hand, the user of protected microdata should obtain most important information on the expected information loss due to SDC process. It enables the assessment of the impact of changes in the original data resulting from the need to protect statistical confidentiality on the quality of the final results of the estimates and analyzes carried out by him/her.

In general, two types of microdata files are released by NSIs, namely public use files (PUF) and research use files (MFR). 
The disclosure risk\index{disclosure risk} in public use files is entirely managed by the design of the file and the application of SDC methods. 
For research use microdata files SDC methods will be applied in addition to some restrictions on access and use, *e.g.* under a licence or access agreement,
such as those provided by Commission Regulation 831/2202, see @sec-laws. 
Necessarily the research release files contain more detail than the public use files.
The estimated expected information loss should be computed both as total and for each variable separately, if possible.

Some NSIs will also provide access to microdata in datalaboratories/research centres or via remote access/execution. 
Datalabs allow approved users on-site access to more identifiable microdata. Typically datalab users are legally prohibited from disclosing information 
and are subject to various stringent controls, *e.g.* close supervision on-site to protect the security of the data and output checking, to assist with disclosure control. 
For remote execution researchers are provided with a full description of the microdata. 
They then send prepared scripts to the NSI who run the analysis, check and return the results. 
Remote access is a secure on-line facility where the researchers connect to the NSI's server (via passwords and other security devices) where the data and programs are located. 
The researchers can submit code for analysis of microdata or in some instances see the files and programs 'virtually' on their desktops. 
Confidentiality protection is by a combination of microdata modification, automatic checks on output requested, manual auditing of output and a contractual agreement. 
The researcher does not have complete access to the whole data itself; however they may have access to a small amount of unit record information for the purpose of seeing the data structure before carrying out their analysis.

@sec-roadmap goes through the whole process of creating a microdata file for external users from the original microdata. 
The aim of such section is to briefly analyse the different stages of the disclosure process providing references to the relevant sections where each step will be described in more details.
@sec-software is dedicated to the software. [Sections @sec-intro-example] and [-@sec-further-example] provide some examples. 
Further and more detailed examples can be found in Case studies available on the CASC website ([https://research.cbs.nl/casc/handbook.htm#casestudies](https://research.cbs.nl/casc/handbook.htm#casestudies)). 
[Chapter 6](06-remote-access-issues.html) of the current handbook provides more details on different microdata access issues such as research centres, remote access/execution and licensing.
