## A roadmap to the release of a microdata file {#sec-roadmap}

This section aims at introducing the reader to the process that, starting from the original microdata file as it is produced by survey specialists, ends with the creation of a file for external users. This roadmap will drive you through the six stage process for disclosure, mostly outlined in @sec-5-stages *i.e.*

1.  why is confidentiality protection needed;
2.  what are the key characteristics and use of the data;
3.  disclosure risk\index{disclosure risk} (ex ante);
4.  disclosure control methods;
5.  implementation;
6.  assessment of disclosure risk\index{disclosure risk} and utility (ex post)

Specifying, for each stage, the peculiarities of microdata release. In @tbl-roadmap we present an overview of the process.

::: {.content-visible unless-format="pdf"}

+:---------------------------------------------------------------------------------+:-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------:+
| **Stage of disclosure process**                                                  | **Analyses to be carried out / problem to be addressed**\                                                                                                                                             |
|                                                                                  | ⇓\                                                                                                                                                                                                    |
|                                                                                  | ***Results expected***                                                                                                                                                                                |
+----------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 1\. Why is confidentiality protection needed                                     | Does the data refer to individuals or legal entity?\                                                                                                                                                  |
|                                                                                  | ⇓\                                                                                                                                                                                                    |
|                                                                                  | *We need to protect the statistical unit*                                                                                                                                                             |
+----------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 2\. What are the key characteristics and use of the data                         | Analysis of the type/structure of the data\                                                                                                                                                           |
|                                                                                  | ⇓\                                                                                                                                                                                                    |
|                                                                                  | *Clear vision of which units need protections*                                                                                                                                                        |
|                                                                                  +-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
|                                                                                  | Analysis of survey methodology\                                                                                                                                                                       |
|                                                                                  | ⇓\                                                                                                                                                                                                    |
|                                                                                  | *Type of sampling frame, sample/complete enumeration of strata, further analysis of survey methodology, calibration*                                                                                  |
|                                                                                  +-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
|                                                                                  | Analysis of NSI objectives\                                                                                                                                                                           |
|                                                                                  | ⇓\                                                                                                                                                                                                    |
|                                                                                  | *Type of release (PUF, MFR),dissemination policies, peculiarities of the phenomenon, coherence between multiple releases (PUF and MFR), coherence with released tables and on-line databases, etc.*   |
|                                                                                  +-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
|                                                                                  | Analysis of user needs\                                                                                                                                                                               |
|                                                                                  | ⇓\                                                                                                                                                                                                    |
|                                                                                  | *Priorities for variables, type of analysis, etc.*                                                                                                                                                    |
|                                                                                  +-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
|                                                                                  | Analysis of the questionnaire\                                                                                                                                                                        |
|                                                                                  | ⇓\                                                                                                                                                                                                    |
|                                                                                  | *List of variables to be removed, variables to be included, some ideas of level of details of structural variables*                                                                                   |
+----------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 3\. Disclosure risk (ex ante)                                                    | Disclosure scenario\                                                                                                                                                                                  |
|                                                                                  | ⇓\                                                                                                                                                                                                    |
|                                                                                  | *List of identifying variables*                                                                                                                                                                       |
|                                                                                  +-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
|                                                                                  | Definition of risk\                                                                                                                                                                                   |
|                                                                                  | ⇓\                                                                                                                                                                                                    |
|                                                                                  | *Risk measure*                                                                                                                                                                                        |
|                                                                                  +-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
|                                                                                  | Risk assessment\                                                                                                                                                                                      |
|                                                                                  | ⇓\                                                                                                                                                                                                    |
|                                                                                  | *If the risk is deemed too high need of disclosure limitation methods*                                                                                                                                |
+----------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 4\. Disclosure limitation methods                                                | Analysis of type of data involved, NSI policies and users needs\                                                                                                                                      |
|                                                                                  | ⇓\                                                                                                                                                                                                    |
|                                                                                  | *Identification of a disclosure limitation method*                                                                                                                                                    |
|                                                                                  +-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
|                                                                                  | Information loss analysis                                                                                                                                                                             |
+----------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 5\. Implementation                                                               | Choice of software, parameters and thresholds for different methods                                                                                                                                   |
+----------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 6\. assessment of disclosure risk\index{disclosure risk} and utility (ex post)   | Ex post analysis of disclosure risk\index{disclosure risk} and information loss\                                                                                                                      |
|                                                                                  | ⇓\                                                                                                                                                                                                    |
|                                                                                  | *In case disclosure risk\index{disclosure risk} and/or utility loss is too high, return to step 4 or 5.*                                                                                              |
+----------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+

: Roadmap to releasing a microdata file {#tbl-roadmap}

:::


::: {.content-visible when-format="pdf"}
\begin{table}
\hspace*{-1cm}%
\begin{tabular}{|l|c|}
\hline
\multirow{3}{*}{\textbf{\begin{tabular}[c]{@{}l@{}}Stage of disclosure \\ process\end{tabular}}} & \textbf{Analyses to be carried out / problem to be addressed}    \\  
& \textbf{$\Downarrow$}   \\  
& \textit{\textbf{Results expected}}   \\ 
\hline
\multirow{3}{*}{\begin{tabular}[c]{@{}l@{}}1. Why is \\ confidentiality \\ protection needed\end{tabular}}  & Does the data refer to individuals or legal entity?    \\    
 & $\Downarrow$      \\   
 & \textit{We need to protect the statistical unit}   \\ 
 \hline
\multirow{15}{*}{\begin{tabular}[c]{@{}l@{}}2. What are the key \\ characteristics and \\ use of the data\end{tabular}}  & Analysis of the type/structure of the data  \\  
 & $\Downarrow$  \\ 
 & \textit{Clear vision of which units need protections}  \\ 
 \cline{2-2} 
 & Analysis of survey methodology \\ 
 & $\Downarrow$  \\   
 & \begin{tabular}[c]{@{}l@{}}\textit{Type of sampling frame, sample/complete enumeration of} \\ \textit{strata, further analysis of survey methodology, calibration}\end{tabular}  \\ 
 \cline{2-2}  
 & Analysis of NSI objectives \\ 
 & $\Downarrow$  \\  
 & \begin{tabular}[c]{@{}l@{}}\textit{Type of release (PUF, MFR),dissemination policies,} \\  \textit{peculiarities of the phenomenon, coherence between} \\  \textit{multiple releases (PUF and MFR), coherence with released} \\  \textit{tables and on-line databases, etc.}\end{tabular}\\ 
 \cline{2-2} 
 & Analysis of user needs   \\  
 & $\Downarrow$  \\ 
 & \textit{Priorities for variables, type of analysis, etc.}  \\ 
 \cline{2-2}  
 & Analysis of the questionnaire  \\  
 & $\Downarrow$  \\  
 & \begin{tabular}[c]{@{}l@{}}\textit{List of variables to be removed, variables to be included,} \\ \textit{some ideas of level of details of structural variables}\end{tabular}  \\ 
 \hline
\multirow{9}{*}{3. Disclosure risk (ex ante)}  & Disclosure scenario  \\ 
 & $\Downarrow$  \\  
 & \textit{List of identifying variables}  \\ 
 \cline{2-2} & Definition of risk \\ 
 & $\Downarrow$  \\ 
 & \textit{Risk measure}  \\ 
 \cline{2-2}  & Risk assessment  \\  
 & $\Downarrow$   \\   
 & \textit{If the risk is deemed too high need of disclosure limitation method}  \\ 
 \hline
\multirow{3}{*}{\begin{tabular}[c]{@{}l@{}}4. Disclosure \\ limitation methods\end{tabular}}    & Analysis of type of data involved, NSI policies and users need \\ 
 & $\Downarrow$  \\ 
 & \textit{Identification of a disclosure limitation method} \\ \hline
$5$. Implementation methods & Choice of software, parameters and thresholds for different methods  \\ 
 \hline
\multirow{3}{*}{\begin{tabular}[c]{@{}l@{}}6. assessment of \\ disclosure risk\index{disclosure risk} \\  and utility (ex post)\end{tabular}} & Ex post analysis of disclosure risk\index{disclosure risk} and information loss   \\ 
 & $\Downarrow$  \\ 
 & \textit{In case disclosure risk\index{disclosure risk} and/or utility loss is too high, return to step 4 or 5.}  \\ 
 \hline
\end{tabular}
\caption{Roadmap to releasing a microdata file}
\label{tbl-roadmap}
\end{table}

:::


The idea is to identify for each stage of the process choices that have to be made, analyses that need to be done, problems that need to be addressed and methods to be selected.
References to the relevant sections where technical topics are discussed in detail will help the beginners in following the process without getting lost in too technical aspects.

We now analyse in turn each of the six stages.

### Need of confidentiality protection

The starting point deals with the need of confidentiality protection which is at the base of any release of microdata. 
If the microdata do not refer to legal entity or individual persons it can be released without confidentiality protection: an example is the amount of rain fall in a region. 
If microdata pertain only of public variables, in most cases they might be released: the legislation usually treats such data as excluded from statistical confidentiality. 
However, in general, data refer to individual or enterprises and contains confidential variables (health related data, income, turnover, expenses, etc.) and therefore need to be protected.

### Characteristics and uses of microdata

Of course different levels of protection are needed for different type of users. This theme leads us to the second stage of the process *i.e.* the study of the key uses and characteristics of the data. 
Here the initial question is whether the microdata file we are going to release is intended for a general public (public use file) or whether it is created for research purpose (research use files). 
In the latter case the microdata will be released according to predefined procedures and legal binding (see also @sec-licensing). 
The difference in user's type implies different user's needs, different disclosure scenarios, different types of analyses we expect to be performed with the released data, different statistics we may intend to preserve and different amount of protection we intend to apply. 
We now analyse all these issues in terms.

*Type and structure of data*\
Analysis of user needs involves first a study of the survey information content. 
This should be done together with a survey expert that has a deeper knowledge of the data, phenomenon and possible types of analysis that can be performed on the data.

Typical questions that need to be addressed are:

*Which statistical units are involved in the survey?* Individuals, enterprises, households, etc. The type of units has a big influence on the risk assessment stage.

*Do data present a particular structure*? Hierarchical data: students inside schools, graduates inside universities, employees inside an enterprise, individual inside household etc.
If this is the case care needs to be taken in checking both levels/types of units involved. 
*E.g.*, do schools/universities/enterprises need to be protected besides students/graduates/employees?

*What type of sampling design has been used?* Are there strata (or units of earlier stages in a two- or multistage sampling design) which have been censured? Of course a complete enumeration of a strata (typical in business surveys) implies different and higher risks than a sample. 
Is two- or multistage sampling used with different types of units in the different stages?

An analysis of the questionnaire is useful to analyse the type of information present in the file: possible identifying variables (of which identifiers and quasi-identifiers), confidential variables and sensitive variables.

*Preliminary work on variables*\
In this stage the setting of objectives from the viewpoint of the NSI and the user are defined. 
From the NSI side dissemination policies are clarified (*e.g.* level of dissemination of NACE, geography, etc. or coherence with published tables). 
From the user point of view a list of priorities in the structural variables of the survey, requests for minimum level of details for such variables and type of analysis to be performed (ratios, weighted totals, regressions, etc).

The characteristics of the phenomenon under study should also be considered as well as the dissemination policy of the Statistical Institute. 
This is particularly true for example in business data where some NACE classifications may never be released by their own, but always aggregated with others. 
Such a-priori aggregations generally depend on the economic structure of the country. 
It is not a sampling or dissemination problem, but rather a feature of the surveyed phenomenon. 
This will bring to aggregation of categories of some identifying variables deemed too detailed.

The output of this questionnaire analysis should be a preliminary list of variables to be removed and those to be released (because relevant to users need) together with some ideas of their level of details (depending on whether we are releasing a public use file or a research use file). 
Some examples to clarify these ideas. 
Variables that shouldn't be released comprise variables used as internal checks (*e.g.* some paradata), flags for imputation, variables that were not validated, variables deemed as not useful because containing too many missing values, information on the design stratum from which the unit comes from etc. 
Obviously also direct identifiers should not be released. 
The case studies A1 and A2 on microdata release provide examples of such stage.

Categories of identifying variables with too significant identifying power are commonly aggregated into a single category.

This is particularly true when releasing public use files as certain variables when too detailed could retain a level of "sensitivity". 
This may not be felt useful and/or appropriate for the general public. 
For example, in an household expenditure survey we might avoid releasing for the public use file very detailed information on the expenditure for housing (mortgage, rent) or detailed information on the age of the house or its number of rooms (when this is very high) as these might be considered as giving too much information for particular outlying cases.

*Geography*\
Another example is related to the level of geographical details that maybe different for a public use file or a research use file (especially if a data limitation technique is used).
This happens because geographical information is a strongly identifying variable. 
Moreover, the geographical information collected from the respondent may be available in different variables for different purposes (place of birth, place of residence, place of work, place of study, commuting, etc.). 
All such geographical details need to be coherent/consistent throughout the file.
To this end it may be convenient releasing relative information instead of absolute one: for example place of residence can be given at a certain detail (*e.g.* region) and then the other geographical information (place of work, study etc.) can be released with respect to this one. 
Examples of possible relative recodings (*e.g.* with respect to region of residence) are: region of work same as region of residence, different region but same macroregion, different macroregion.

*Coherence with published tables*\
At this initial stage of the analysis information should be collected on what has already been published/what it is going to be released from the microdata set: dissemination plan, which type of tables and what classification/aggregation was used for the variables. 
This is to avoid different classifications in different release: the geographical breakdown, as well as classification of other variables in the survey (*e.g.* age, type of work etc.), should be coherent with the published marginals. 
For example, if a certain classification of the variable age is published in a table the microdata file should use a classification which has compatible break points so that to avoid gaining information by differencing. 
Release of date of birth is highly discouraged. 
Also, as far as possible, published totals should be preserved for transparency.

### Disclosure risk (ex ante)

Moreover, in case of multiple release of the same survey (*e.g.* PUF and microdata for research) coherence should be maintained also between different released files in the sense that releasing different files at the same time shouldn't allow the gaining of more information than for one file alone (see, Trottini et al., 2006). 
The principles apply also to the release of longitudinal or panel microdata, where the differences between records pertaining to the same case in different waves will reflect 'events' that have occurred to that case, as well as the attributes of the individuals.

Once the characteristics and uses of the survey data are clear, it is time to start the real analysis of the disclosure risk\index{disclosure risk} in relation to files with originally collected data -- *ex ante* assessment (in one of next subsections we will indicated also on a necessity of making *ex post* assessment of disclosure risk\index{disclosure risk} to verify effciency of used SDC methods).
This implies first a definition of possible situations at risk (disclosure scenarios) and second a proper definition of the 'risk' in order to quantify the phenomenon (risk assessment).

*Disclosure scenario*\
A disclosure scenario is the definition of realistic assumptions about what an intruder might know about respondents and what information would be available to him to match against the microdata to be released and potentially make an identification and disclosure.

Again different types of releases may require different disclosure scenarios and different definitions of risk. 
For example the nosy neighbourhood scenario described in @sec-disclosure-risk-scenarios, possibly with knowledge of the presence of the respondent in the sample (implying that sample uniques are a relevant quantity of interest for risk definition), may be deemed adequate for a public use file. 
A different trust might be put in a researcher that needs to perform an analysis for research purposes.
This implies, as a minimum step, a higher level of acceptable risk and a different scenario the spontaneous identification scenario.

*Spontaneous recognition*\
Spontaneous recognition is possible when the researchers unintentionally recognize some units. 
For example, when releasing enterprise microdata, it is publicly known that the largest enterprises are generally included in the microdata file because of their significant impact on the studied phenomenon. 
Moreover, the largest enterprises are also the most identifiable ones as recognisable by all (the largest car producer factory, the national mail delivery enterprise, etc.). 
Consequently, a spontaneous identification or recognition might occur. A description of different scenarios is presented in @sec-disclosure-risk-scenarios; examples of spontaneous identification scenarios for MFR are reported in case studies A1 and A2.\ 

*Definition of risk*\
From the adopted scenario we can extract the list of identifying variables *i.e.* the variables that may allow the identification of a unit. 
These will be the basis for defining the risk of disclosure. 
Intuitively, a unit is at risk of identification when it cannot be confused with several other units. 
The difficulty is to express this simple concept using sound statistical methodology.

Different approaches are used if the identifying variables are categorical of continuous. 
In the former case at the basis of the definition is the concept of a 'key' (*i.e.* the combination of categories of the identifying variables): see @sec-risk-overview for a classification of different definitions. 
Whereas if continuous identifying variables are present in the file a possibility is to use the concept of density: see Ichim (2009) for a detailed analysis of definitions of risk in the case of continuous variables. 
Of course, the problem is even more complicated when we deal with a mixture of categorical and numerical key variables; for an example of this situation (quite common in enterprise microdata) see case study A1 (Community Innovation Survey).
Another solution in this context can be the assessment of disclosure risk\index{disclosure risk} based on the (expected) number of units for which a value of the given continuous variable falls into the respectively defined (using established threshold of deviation) neighborhood of a given observation. 
This approach can be perceived as some variation of $k$-anonymity in this case.\

*Risk assessment*\
Once a formal definition of risk has been chosen we need to measure/estimate it. 
There are several possibilities for categorical identifying variables (these are reported in various subsections of @sec-risk-assessment) and for a mixture of categorical and continuous identifying variable we have already mentioned Case study A1. 
The final step of the risk assessment is the definition of a threshold to define when a unit or a file presents an acceptable risk and when, on the contrary, it has to be considered at risk. 
This threshold depends of course on the type of measure adopted and details on how to choose a threshold are reported in the relevant subsequent sections.

Choice of scenarios and level of acceptable risk are extremely dependent on different cultural situations in different member states, different policies applied by different institutes, different approaches to statistical analysis, different perceived risk. 
To this end it must be stressed that different countries may have extremely different situation/phenomenon therefore different scenarios and risk methods are indeed necessary.

Currently there is no general agreement on which risk methodology is best although different methods give in general similar answers for the extreme cases. 
However, as already stated in @sec-risk-overview, there is a strong need to further compare and understand differences between available methods. 
Pros and cons of each method are described in the relevant sections may be used as a guidelines for the most appropriate choice of the risk estimation in different situations. 
Further advice can be gained by studying of the examples and case studies.

### SDC-methods

If the risk assessment stage shows that the disclosure risk\index{disclosure risk} is high then the application of statistical disclosure limitation methods is necessary to produce a microdata file for external users.

*Masking methods*\
Microdata protection methods can generate a protected microdata set either by *masking original data*, *i.e.* generating a modified version of the original microdata set or by *generating synthetic data* that preserve some statistical properties of the original data. Synthetic data are still difficult to implement; a description can be found in @sec-synthetic-data. 
Masking methods are divided into two categories depending on their effect on the original data (Willenborg and De Waal, 2001): *perturbative* and *non perturbative masking* methods.

Perturbative methods either modify the identifying variables or modify the confidential variables before publication. 
In the former way, unique combinations of scores of identifying variables in the original dataset may disappear and new unique combinations may appear in the perturbed dataset. 
In this way a user cannot be certain of an identification. 
Alternatively confidential variables can be modified; in this case even if an identification occurs, the wrong value is associated and disclosure of the original value is avoided (for an example of this case see case study A2). 
For a description of a variety of perturbative methods see sections [-@sec-perturbative-masking], [-@sec-noise-addition-details], [-@sec-microaggregation-further] and [-@sec-PRAM].

Non-perturbative methods do not alter the values of the variables (either identifying or confidential); rather, they produce a reduction of detail in the original dataset. 
Examples of non-perturbative masking are presented in @sec-nonperturbative-masking.

The choice between a data reduction and a data perturbation method strongly depends on the policy of an institute and on the type of data/survey to be released. 
While the policy of an institute is outside of this debate, technical reasons may suggest the use of perturbative methods for the protection of continuous variables (mainly business data). 
Analysis of information loss should always be part of the selection process. 
The usual difference between types of release remains valid and it is linked to the difference between users needs. 
Again the examples and the case studies A1 and A2 may help in clarifying different situations.

*User needs and types of protection*\
From the needs of the users and the types of analyses that could be performed on the data one could gain information for the choice of the type of protection that could be applied to the microdata. 
Also users could express priorities in the need of maintaining some variables intact (*e.g.*, for business usually NACE is the most important variable, then employees, and so on).

*Information loss*\
For research purposes maybe we could be interested in maintaining the possibility of being able to reproduce the published tables. 
For a public use file maybe we could avoid, as much as possible, the use of local suppression as this may render data analysis difficult for non sophisticated users. 
In general, the implementation of perturbative methods should take into account what variables and relationships among them need to be kept from the user point of view. 
An assessment of information loss caused by the protection methods adopted is highly recommended. 
A brief description of information loss measures is reported in @sec-informationloss-microdata; examples of how to check in practice the amount of distortion or modification in the protected microdata is presented in case studies A1 and A2.

Finally, every time a data perturbation method is applied attention should be placed at relationships between different types of release (PUF, MFR, tables) so as to avoid as much as possible, different marginal totals from different sources.

An example of the application of this reasoning for the definition of a dissemination strategy can be found, for example, in Trottini et al. (2006).

### Implementation

The next stage of the SDC process is the implementation of the whole procedure, choice of software, parameters and levels of acceptable risks.

Documentation is an essential part of any dissemination strategy both for auditing from external authorities and transparency towards users. 
The former may include description of legal and administrative steps for a risk management policy together with the technical solution applied. 
The latter is essential for a user to understand what has been changed or limited in the data because of confidentiality constraints. 
If a data perturbation method has been applied then, for transparency reasons, this should be clearly stated. 
Information on which statistics have been preserved and which have been modified and some order of magnitude of possible changes should be provided as far as possible. 
If a data reduction method has been applied with some local suppression then the distribution of such suppressions should be given for a series of different dimensions of interest (distribution by variables, by household size, household type, etc.) and any other statistics that are deemed relevant for the user. 
The released microdata should be obviously accompanied by all necessary metadata and information on methodologies used at various stage of the survey process (sampling, imputation, validation, etc.) together with information on magnitude of sampling errors, estimation domains etc.

### Ex post assessment of disclosure risk\index{disclosure risk} and information loss\index{information loss}

The last - but, of course, not least - stage of the procedure is the ex post assessment of disclosure risk\index{disclosure risk} and computation of the expected information loss\index{information loss} due to SDC. 
The ex post risk assessment (usually made using the same measures as in the case of ex ante assessement, for comparability) allows for confirmation whether the used procedure eliminates or sufficiently reduces the threat of unit identification or not. 
If not, a modification of used methods (*e.g.* by changing some tools, modification of parameters, etc.) should be made. This means back to either the step "Disclosure limitation methods" or the step "Implementation".

An assessment of information loss caused by the applied protection methods is highly recommended. 
The knowledge of possible loss of information is key for data utility for possible users. If the information loss is too great then the used methods or their parameterization should be changed (coming back to step "Disclosure limitation methods"). One should remain that simultaneously the disclosure risk\index{disclosure risk} should be also as small as possible. Thus, these quantities should be harmonized. 
A detailed description of information loss measures is reported in @sec-informationloss-microdata; examples of how to check in practice the amount of distortion or modification in the protected microdata is presented in case studies A1 and A2.

Of course, the results of computation of discloure risk (both final and indirect, if applicable) and information loss should be saved in the documentation of the whole process. However, whereas the values of measures of disclosure risk are confidential and known only by entitled staff of the data holder, the level of expected information loss should be made available to the user. It is a very important factor influencing the quality of the final analysis results obtained by him/her.
