## References

Antal, L., Shlomo, N., & Elliot, M. (2014). Measuring disclosure risk\index{disclosure risk} with entropy in population based frequency tables. In *Privacy in Statistical Databases: UNESCO Chair in Data Privacy, International Conference, PSD 2014, Ibiza, Spain, September 17-19, 2014. Proceedings* (pp. 62-78). Springer International Publishing.

Box, G. E. P. and Cox, D. R. (1964) *An analysis of transformations*, Journal of Royal Statistical Society, Series B, vol. 26, pp. 211---252.

Castro, J.(2002), *Network flows heuristics for complementary cell suppression\index{cell suppression}: an empirical evaluation and extensions*, in LNCS 2316, Inference Control in Statistical Databases, J. Domingo-Ferrer (Ed), (2002) 59--73.

Castro, J. (2003 a), *Minimum-Distance Controlled Perturbation Methods for Large-Scale Tabular Data Protection*, accepted subject to revision to European Journal of Operational Research, 2003.

Castro, J. (2003 b) *User's and programmer's manual of the network flows heuristics package for cell suppression\index{cell suppression} in 2D tables*. Technical Report DR 2003-07, Dept. of Statistics and Operations Research, Universitat Politècnica de Catalunya, Barcelona, Spain,2003; See [https://research.cbs.nl/casc/deliv/41D6_NF1H2D-Tau-Argus.pdf](https://research.cbs.nl/casc/deliv/41D6_NF1H2D-Tau-Argus.pdf).

Castro, J. (2006). *Minimum-distance controlled perturbation methods for large-scale tabular data protection*, European Journal of Operational Research, 171, 39--52.

Castro, J., Giessing S. (2006a). *Testing variants of minimum distance controlled tabular adjustment*, in Monographs of Official Statistics. Work session on Statistical Data Confidentiality, Eurostat-Office for Official Publications of the European Communities, Luxembourg, 2006, pp. 333-343.

Catro, J., Giessing S. (2006b). *Quality issues minimum distance controlled tabular adjustment*, paper presented at the European Conference on Quality in Survey Statistics (Q2006), 24.-26. April 2006 in Cardiff.

Catro, J., Gonzalez J.A. (2009). *A Package for L1 Controlled Tabular Adjustment*, paper presented at the Joint UNECE/Eurostat Work Session on Statistical Data Confidentiality (Bilbao, 2-4 December 2009).

Cox, L. (1981), *Linear Sensitivity Measures in Statistical Disclosure Control*, Journal of Planning and Inference, 5, 153 - 164, 1981.

Cox, L. (2001), *Disclosure Risk for Tabular Economic Data*, In: Doyle, Lane, Theeuwes, Zayatz (Eds) Confidentiality, Disclosure, and Data Access: Theory and Practical Applications for Statistical Agencies, North-Holland.

Cox, L., Dandekar, R.H., (2002), *Synthetic Tabular Data -- an Alternative to Complementary Cell Suppression*, unpublished manuscript.

Cox, L. H., Kelly, J. P., and Patil, R. (2004), *Balancing quality and confidentiality for multivariate tabular data*, Lecture Notes in Computer Science, 3050, 87--98.

Cox, L., Orelien, J. G., Shah, B. V. (2006), *A Method for Preserving Statistica Distributions Subject to Controlled Tabular Adjustment*, In: Domingo-Ferrer, Franconi (Eds.): Privacy in Statistical Databases 2006, Lecture Notes in Computer Science, Vol. 4302, Springer, Heidelberg (2006), p.1-11.

De Wolf, P.P. (2002), *HiTaS: A Heustic Approach to Cell Suppression in Hierarchical Tables*, In: Domingo-Ferrer (Ed.) Inference Control in Statistical Databases, Springer (Lecture notes in computer science; Vol. 2316).

De Wolf, P.P. (2007), *Cell suppression in a special class of linked tables*, paper presented at the Joint ECE/Eurostat Worksession on Statistical Confidentiality in Manchester, December 2007, available at
[https://unece.org/sites/default/files/datastore/fileadmin/DAM/stats/documents/ece/ces/2007/12/confidentiality/wp.21.e.pdf](https://unece.org/sites/default/files/datastore/fileadmin/DAM/stats/documents/ece/ces/2007/12/confidentiality/wp.21.e.pdf).

De Wolf, P.P., Giessing, S. (2008) *How to make the $\tau$‑ARGUS Modular Method Applicable to Linked Tables*. In: Domingo-Ferrer, Josep; Saygin, Yücel (Eds.): Privacy in Statistical Databases 2008, Lecture Notes in Computer Science , Vol. 5262, Springer, Heidelberg (2008), p.227-238.

Enderle, T., Giessing, S., Tent, R. (2018), *Designing Confidentiality on the Fly Methodology – Three Aspects*, In: Domingo-Ferrer, J., Montes, F. (eds) Privacy in Statistical Databases. PSD 2018. Lecture Notes in Computer Science, vol 11126. Springer, Cham. [https://doi.org/10.1007/978-3-319-99771-1_3](https://doi.org/10.1007/978-3-319-99771-1_3).

Enderle, T., Giessing, S., Tent, R. (2020), *Calculation of risk probabilities for the cell key method*, In: Doming-Ferre, J., Muralidhar, K. (eds) Privacy in Statistical Databases. PSD 2020. Lecture Notes in Computer Science, vol 12276. Springer, Cham. [https://doi.org/10.1007/978-3-030-57521-2_11](https://doi.org/10.1007/978-3-030-57521-2_11).

EU (2004), *Community statistics relating to the trading of goods between Member States*, [https://eur-lex.europa.eu/LexUriServ/LexUriServ.do?uri=CELEX:32004R0638:EN:HTML](https://eur-lex.europa.eu/LexUriServ/LexUriServ.do?uri=CELEX:32004R0638:EN:HTML).

Fraser, B. and Wooton, J. (2005), *A proposed method for confidentialising tabular output to protect against differencing* Work session on Statistical Data Confidentiality, [https://www.unece.org/fileadmin/DAM/stats/documents/ece/ces/ge.46/2005/wp.35.e.pdf](https://www.unece.org/fileadmin/DAM/stats/documents/ece/ces/ge.46/2005/wp.35.e.pdf).

Geurts, J. (1992), *Heuristics for Cell Suppression in Tables*, working paper, Netherlands Central Bureau of Statistics.

Giessing, S. and Repsilber, D. (2002), *Tools and Strategies to Protect Multiple Tables with the GHQUAR Cell Suppression Engine*, In: Domingo-Ferrer (Ed.) Inference Control in Statistical Databases, Springer Lecture Notes in Computer Science Vol. 2316.

Giessing, S. (2004), *Survey on methods for tabular protection in ARGUS*, Lecture Notes in Computer Science. Volume Privacy in statistical databases 3050, 1­13, J. Domingo-Ferrer and V. Torra, Springer, Berlin.

Giessing, S., Dittrich, S., Gehrling, D., Krüger, A., Merz, F.J., Wirtz, H. (2006), *Bericht der Arbeitsgruppe „Geheimhaltungskonzept des statistischen Verbundes, Pilotanwen­dung: Umsatzsteuerstatistik"*, document for the meeting of the „Ausschuss für Organisation und Umsetzung", Mai 2006, in German.

Giessing, S., Hundepool, A., Castro, J. (2007) *Rounding Methods for Protecting EU-aggregates*, proceedings of the Joint UNECE/Eurostat Worksession on Statistical Confidentiality in Manchester, December 2007.

Fischetti, M, Salazar Gonzales, J.J. (2000), *Models and Algorithms for Optimizing Cell Suppression Problem in Tabular Data with Linear Constraints*, in Journal of the American Statistical Association, Vol. 95, pp 916.

Hundepool. A., Domingo-Ferrer. J., Franconi, L., Giessing S., Nordholt, E.S., Spicer, K. and de Wolf, P-P. (2012), *Statistical Disclosure Control*, series: Wiley Series in Survey Methodology, John Wiley & Sons, Ltd., Chichester. ISBN: 978-1-119-97815-2.

Hundepool, A, Wetering, A van de, Ramaswamy, R, Wolf, P.P. de, Giessing, S, Fischetti, M, Salazar, JJ, Castro, J, Lowthian, P, (2014), *$\tau$-ARGUS 4.1 user manual*, Statistics Netherlands, Voorburg NL, Feb. 2014. [https://research.cbs.nl/casc/Software/TauManualV4.1.pdf](https://research.cbs.nl/casc/Software/TauManualV4.1.pdf).

Ichim, D., Franconi, L. (2006), *Calibration estimator for magnitude tabular data protection*, Proceedings of the conference Privacy in Statistical Databases 2006, December 2006, Rome, Italy.

Loeve, A. (2001), *Notes on sensitivity measures and protection levels*, Research paper, Statistics Netherlands, available at [https://research.cbs.nl/casc/Related/marges.pdf](https://research.cbs.nl/casc/Related/marges.pdf).

Meindl, B. *Linking Complementary Cell Suppression and the Software R*, paper presented at the New Techniques and Technologies (NTTS) Conference, 18.-20. Feb. 2009 in Brussels.

Salazar, J.J. (2003) *Partial Cell Suppression: a New Methodology for Statistical Disclosure Control*, Statistics and Computing, 13, 13-21.

Shlomo, N., Antal, L., & Elliot, M. (2015). *Measuring disclosure risk\index{disclosure risk} and data utility for flexible table generators*. Journal of Official Statistics, 31(2), 305-324.

Repsilber, R. D. (1994), *Preservation of Confidentiality in Aggregated data*, paper presented at the Second International Seminar on Statistical Confidentiality, Luxembourg, 1994.

Repsilber, D. (2002), *Sicherung persönlicher Angaben in Tabellendaten*, In: Statistische Analysen und Studien Nordrhein-Westfalen, Landesamt für Datenverarbeitung und Statistik NRW, Ausgabe 1/2002 (in German).

Thompson, Gwenda/Broadfoot, Stephen/Elazar, Daniel (2013), *Methodology for the Automatic Confidentialisation of Statistical Outputs from Remote Servers at the Australian Bureau of Statistics*, Paper presented at the Joint UNECE/Eurostat Work Session on
Statistical Data Confidentiality. Ottawa 2013. See [https://www.unece.org/fileadmin/DAM/stats/documents/ece/ces/ge.46/2013/Topic_1_ABS.pdf](https://www.unece.org/fileadmin/DAM/stats/documents/ece/ces/ge.46/2013/Topic_1_ABS.pdf).

Van der Meijden, R., (2006)‚ *Improving confidentiality with $\tau$‑ARGUS by focussing on clever usage of microdata*, In: Monographs of Official Statistics. Work session on Statistical Data Confidentiality, Eurostat-Office for Official Publications of the European Communities, Luxembourg, 2006, pp. 363-370.

Wolf, P.P. de (2002). *HiTaS: a heuristic approach to cell suppression\index{cell suppression} in hierarchical tables*, In: Domingo-Ferrer (Ed.) Inference control in statistical databases, from theory to practice, Springer, LNCS 2316, pp. 74--82.


