## References

Antal, L., Shlomo, N., & Elliot, M. (2014) *Measuring disclosure risk with entropy in population based frequency tables*, In *Privacy in Statistical Databases: UNESCO Chair in Data Privacy, International Conference, PSD 2014, Ibiza, Spain, September 17-19, 2014. Proceedings* (pp. 62-78). Springer International Publishing.

Antal, L., & Shlomo, N., & Elliot, M. (2015), *Disclosure Risk Measurement with Entropy in Sample Based Frequency Tables*, New Techniques and Technologies for Statistics (NTTS) Reliable Evidence for a Society in Transition, Brussels, Belgium, 9-13 March 2015, https://cros-legacy.ec.europa.eu/system/files/Antal-etal_NTTS%202015%20abstract%20unblinded%20disclosure%20risk%20measurement.pdf.

Brown, D., (2003) *Different approaches to disclosure control problems associated with geography, ONS*, United Nations Statistical Commission and Economic Commission for Europe Conference of European Statisticians, Working Paper No. 14.

Costemalle, V. (2019). *Detecting geographical differencing problems in the context of spatial data dissemination*. *Statistical Journal of the IAOS, vol. 35, No. 4, pp. 559-568*.

Doyle, P., Lane, J.I., Theeuwes, J.J.M. and Zayatz, (2001). *Confidentiality, Disclosure and Data Access: Theory and Practical Application for Statistical Agencies*. Elsevier Science BV.

Duke-Williams, O. and Rees, P., (1998) *Can Census Offices publish statistics for more than one small area geography? An analysis of the differencing problem in statistical disclosure*, International Journal of Geographical Information Science 12, 579-605

Enderle, T., Giessing, S., Tent, R., (2020) *Calculation of Risk Probabilities for the Cell Key Method. In: Domingo-Ferrer, J., Muralidhar, K. (eds) Privacy in Statistical Databases*, Lecture Notes in Computer Science, vol 12276. Springer, Cham. [https://doi.org/10.1007/978-3-030-57521-2_11](https://doi.org/10.1007/978-3-030-57521-2_11)

Gomatam, S. and A. Karr (2003), *Distortion Measures for Categorical Data Swapping,* Technical Report Number 131, National Institute of Statistical Sciences.

Lupp, D. P., & Langsrud, Ø. (2021). *Suppression of directly-disclosive cells in frequency tables*, In Joint UNECE/Eurostat Expert Meeting on Statistical Data Confidentiality, Poznań, 1-3 December 2021 (pp. 1-3)

Möhler, M., Jamme, J., De Jonge, E., Młodak, A., Gussenbauer, J., De Wolf, P.-P. (2024), *Guidelines for Statistical Disclosure Control Methods Applied on Geo-Referenced Data*, EU Grant agreement 899218 – 2019-BG-Methodology \'STACE project\' , Deliverable D2.9, https://github.com/sdcTools/GeoSpatialGuidelinesSources/releases .

Salazar, JJ, Staggermeier, A and Bycroft, C, (2005) *Controlled rounding implementation*, Proceeding of the Joint UNECE/Eurostat Work Session on Statistical Data Confidentiality, Geneva

Shlomo, N. (2007) Statistical Disclosure Control Methods for Census Frequency Tables. International Statistical Review, Volume 75, Number 2, August 2007 , pp. 199-217(19) Blackwell Publishing.

Shlomo, N. and Young, C. (2005) *Information Loss Measures for Frequency Tables*, Proceeding of the Joint UNECE/Eurostat Work Session on Statistical Data Confidentiality, Geneva.

Shlomo, N. and Young, C. (2006) *Statistical Disclosure Control Methods Through a Risk-Utility Framework*, PSD\'2006 Privacy in Statistical Databases, Springer LNCS proceedings, to appear.

Willenborg, L., and Ton de Waal. (1996) *Statistical Disclosure Control in Practice.* Lecture Notes in Statistics no 111 Springer-Verlag. New York.
