## Confidentiality protection of the analysis results

### Output checking

Output checking is the process of checking the disclosure risk of research results based on microdata files made available in RDCs. NSIs and other institutions can establish their own rules for output checking.

In 2009, a document \'Guidelines for the checking of output based on microdata research\' was prepared within the European project ESSnet SDC. In 2015, this document was a basis for a document \'Guidelines for Output Checking\' prepared within the DwB (Data without Boundaries) project. Both documents provide guidelines and practical advice for output checkers. Principles-based model and rule-of-thumb model are described; the former considers the entire context of the output, while the latter is based on strict rules. The overall rule of thumb is defined and its application to different types of output is described. Organisational aspects of output checking are discussed.

### Basic rules concerning the program code: Example from German oﬀicial statistics

#### Introduction

As in many other countries, German oﬀicial microdata are subject to strict data protection regulations. Therefore, results produced on the basis of statistical microdata are checked for confidentiality risks and critical values are suppressed or altered. This applies both to publications of the Statistical Oﬀices and to results that are generated by researchers via the Research Data Centres (RDC) of German oﬀicial statistics.

The RDC offer the scientific community a wide variety of data from different statistics. Since the RDC were established in Germany in 2001, microdata requests have considerably increased and analyses are getting more and more complex. Thus, the checks for statistical disclosure control, which are mostly done manually[^9], became a very time-consuming and labour-intensive part of RDC work. Experience from several hundred research projects has shown that those confidentiality checks can be accomplished easier if the program code and the resulting output structure follow a given set of rules. To make the application of these rules as user friendly as possible, the RDC of German official statics developed sample program codes for different programming languages (see [https://www.forschungsdatenzentrum.de/en/confidentiality](https://www.forschungsdatenzentrum.de/en/confidentiality)).

[^9]: A mostly manual handling of the confidentiality check has several disadvantages (inefficient, possible mistakes, …) but, in contrast to automated systems, it does not completely block certain procedures and commands but allows individual decisions: when calling up critical procedures, and depending on the data or the specific analysis, the RDC staff can decide to what extent the analysis results can be transmitted to the user or be retained for confidentiality reasons. Necessary changes can easily be communicated to the user.

The purpose of the rules and the sample program codes is

-   to make program code easily and quickly understandable,
-   to include all necessary information for the output check,
-   to clearly indicate the relations between different sets of output,
-   to facilitate readability,
-   to differentiate between output for release and output that is only created for the confidentiality check,
-   to apply uniform standards to projects performed at different locations of the RDC,
-   to thus reduce the time it takes to check an output,
-   and, where necessary, to enable a smooth change of the project staff at the RDC without causing delays in the project progress.

#### Rules for program design

The rules that have to be applied by the data users are stated below. They are an outline of the RDC’s “Regulations on the analysis of microdata".[^10]

[^10]: Research Data Centres of the Federal Statistical Office and the Statistical Offices of the Federal States: Regulations on the analysis of microdata in the Research Data Centres of the Federal Statistical Office and the Statistical Offices of the Federal States (RDC). Düsseldorf, 2022. See [https://www.forschungsdatenzentrum.de/en/confidentiality](https://www.forschungsdatenzentrum.de/en/confidentiality) 

_**Clear Structure**_

The program code has to be written with a clear structure and all program steps have to be comprehensible. A master program code is to be used if the code is separated into several files. All specifications that have to be adjusted by the RDC to execute the program code (path specification, name of the dataset, …) are to be stated only once and in the header of the (master) program code. 

_**Detailed commentary**_

All steps for preparation and analysis of the data have to be commented reasonably and in detail. Their content has to be described.

_**Uniqueness of variable and value labels**_

Variable and value labels have to be assigned uniquely and with descriptive names. If a new variable is created or if an existing variable is adjusted then all related labels have to be assigned newly and to be stated in the header of the program code.

_**Reproducibility of the output**_

All output has to be identically reproducible by the associated program code. The logging has to be switched on at the beginning of the code and may not be switched off at any time.

_**Specification of the output formats**_

All tabular and analytical results are to be saved in a processable format so the RDC are able to conduct to the confidentiality check. In contrast, all graphical results have to be saved in a non-processable format to prevent underlying values or numbers of cases to be released.

_**Marking of output to be released and output for the confidentiality check**_

The RDC distinguish between output that is to be checked by the RDC staff and released for publication and output that is generated only for the conduction of the confidentiality check. Both output categories and their relations have to be unambiguously marked.

_**Output of the underlying numbers of cases and marking of the relations**_

For all output that is to be released, the underlying unweighted number of cases is to be stated. If diagrams and graphics are to be released then additional tables with the depicted values and the underlying unweighted numbers of cases have to be stated and to be marked unambiguously.

_**Output of difference groups and marking of relations**_

If results for one or more associated and not overlapping subgroup(s) are created in addition to results for the whole population then the results for the remaining (possibly summarised) subgroup(s) always have to be stated as well. Missing values should preferably be stated separately to avoid difference problems in the following analyses. In case of overlapping sub-groups the number of cases has to be stated for every intersection.

_**Output of certain values for the check for dominance and marking of relations**_

If value tables (sums) are created then the number of cases and the highest two individual values have to be stated. [Note: In Germany, this only applies to economic or tax statistics.]

_**Non-redundancy of statistical results**_

In the course of a project, identical statistical results may only be marked for release once. If results have to be released again in duly substantiated exceptional cases, an exact reference to the according earlier analysis has to be made.
